before_all do |lane , options|
    puts "Run all lane with type #{options[:env]}"
end

platform :android do   
    desc 'Build the Android application.'
    lane :deploy do | options |
        gradlePath= "android/app/build.gradle"
        versionCode= increment_version_code( gradle_file_path:gradlePath)
        git_commit(path: gradlePath, message:  "Version for bump: #{versionCode}")
        
        puts "Start build apk"
        gradle(
            task: "clean", 
            project_dir: 'android/',
            properties: {
                "defaultEnvFile" => ENV["ENVFILE"]
            }
        )
        gradle(
            task: "assemble",
            build_type: "Release",
            flavor: ENV["FLAVOR"],
            print_command: true,
            project_dir: 'android/',
            properties: {
                "defaultEnvFile" => ENV["ENVFILE"]
            }
        )
        
        diawi(
            token:  ENV["DIAWI_TOKEN"]
        )  
    end

end

platform :ios do   
    desc 'Build the iOS application.'
    lane :deploy do | options |
        increment_build_number(xcodeproj: './ios/ReactNativeTS.xcodeproj')
      
        build_app(
            configuration: "Release",
            scheme: ENV["SCHEME"],
            workspace: "ios/ReactNativeTS.xcworkspace", 
            export_method: "app-store",
        )
        upload_to_testflight(skip_waiting_for_build_processing: true)
        commit_version_bump(message: 'Bump build', xcodeproj: './ios/ReactNativeTS.xcodeproj')
    end
end

after_all do
    puts "Build success"
    # push_to_git_remote
end